services:
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - elk

  kibana:
    image: kibana:8.12.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest #v2.46.0
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
    - elk
    
volumes:
  elasticsearch-data:
  prometheus-data:

networks:
  elk:
    driver: bridge
