###############################################
#Arquivo application.yml
#Configuração do Spring Boot para endpoints de gerenciamento:
# - Expõe endpoints de saúde, métricas e integração com Prometheus via web.
# - Configura detalhes do endpoint de saúde para mostrar sempre os detalhes.
###############################################

management:
  endpoints:
    web:
      exposure:
        # Define quais endpoints de gerenciamento (actuator) estarão expostos via HTTP
        # Aqui estão expostos os endpoints de health (saúde), metrics (métricas) e prometheus (métricas no formato Prometheus)
        include: 'health, metrics, prometheus'  # Pode usar '*' para expor todos os endpoints

  endpoint:
    health:
      # Configura o endpoint health para sempre mostrar detalhes completos no retorno,
      # útil para monitoramento detalhado do estado da aplicação
      show-details: always

spring:
  elasticsearch:
    uris: http://elasticsearch:9200