global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "api-products"
    metrics_path: /actuator/prometheus #metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-products"
